### ISSUE TITLE
Black Box Testing

### ISSUE THREAD

**Issue by DKelly01** [IsaacMSchultz/CptS_422_Project#19]
#19 
* Develop fault models for each check first and include this as a document. (What is a fault model?)
* Develop test cases (snippets of codes) according to your fault models. Name and number them in a organized way.
# Individual Classes
1. Lines of Comments Count
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
2. Expression Count
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
3. External Method Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
4. Halstead Difficulty Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
5. Halstead Effort Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
6. Halstead Length Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
7. Halstead Vocabulary Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
8. Halstead Volume Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
9. Number of Comments Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
10. Local Method Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
11. Maintainability Index
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
12. MaxNumLoops Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
13. Number of Casts Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
14. Operand Count Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
15. Operator Count Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)
16. Variable Count Check
    - [x] Fault Model
    - [x] Test Cases (Code snippets)

**Comment by IsaacMSchultz** [comment]
Drew: first 5
Sean: 6-10
Isaac:, 11-15
Kenzo: 16-20
